### ISSUE TITLE
Login Tokens Table

### ISSUE THREAD

**Issue by dillmo** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#15]
We can authenticate users by giving them a token when they login. They can send that token with every API request to prove they are who they say they are. Add a Token table to the database that establishes a one-to-many relationship between Users and Tokens.

**Comment by LeonCChen** [comment]
3/28/2021 - Updated the Database and added/updated the USER table and TOKEN table with a One to Many relationship between the USER table and the TOKEN table.

**Comment by LeonCChen** [comment]
9b77de309da60268863b653d568343128cbc857c

**Comment by LeonCChen** [comment]
Fully Working - 112dd4fda2a7ddc7315142f8ad04b222d61a3746
