### ISSUE TITLE
User Salt API Method

### ISSUE THREAD

**Issue by dillmo** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#16]
We can authenticate users by giving them a token when they login. They can send that token with every API request to prove they are who they say they are. The first step of logging in is getting a user's salt. Create an API method that accepts an email and returns the salt associated with that email. It will be necessary to ensure emails cannot be duplicated in the database User table.

**Comment by LeonCChen** [comment]
Completed 6f08fdd806ed3ba8f0062c0a342e6b6ecaf30c55
