### ISSUE TITLE
User Login API Function

### ISSUE THREAD

**Issue by dillmo** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#17]
We can authenticate users by giving them a token when they login. They can send that token with every API request to prove they are who they say they are. Create an API function that accepts an email and password hash and, if they are in the database Users table under the same User, creates a Token for the User in the database and returns it.

**Comment by LeonCChen** [comment]
Completed get_token function
8c8b2ded72d5da42a94682627c54e0991475d246 - Edit
4c93d849dd89d9f9dbac7f2f0ba724d06cb3fad8 - Edit
ba7ab85efb6d8bd5ff479131d11872b1fa8ae432 - Code
