### ISSUE TITLE
Manage Account

### ISSUE THREAD

**Issue by ferreirak3atwit** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#21]
Manage User account: 
2.1.1.1. Create User Account: 
       [REQ-1] The system shall allow users to create new accounts with their email address.  
       [REQ-2] The system shall send a welcome email when a user creates an account. 
2.1.1.2. Edit User Account: 
       [REQ-3] The system shall allow users to edit their account information provided during registration such as name, email 
        address, etc. 
       [REQ-4] The system shall allow users to delete their accounts.

**Comment by ferreirak3atwit** [comment]
Fixed name to match with the label.

**Comment by dillmo** [comment]
Closed by [9686e26](https://github.com/WIT-Spring-2021-Software-Eng-Group-6/smart-report/commit/9686e262ad1af798aec3ff5a070bf7fdf48e0022).
