### ISSUE TITLE
Edit News Sources API

### ISSUE THREAD

**Issue by dillmo** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#24]
Edit News Sources:

The system shall allow users to edit (add or remove) news sources (RSS feeds) that have been personalized for their accounts.

**Comment by LeonCChen** [comment]
"Done" - BUG**
dfb3f2639d0bed3bdd2827fc8b6b96dcb833c747

**Comment by LeonCChen** [comment]
0085a60
Dillon Helped with the API Functions
