### ISSUE TITLE
Edit account information API

### ISSUE THREAD

**Issue by dillmo** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#25]
[REQ-3] The system shall allow users to edit their account information provided during registration such as name, email address, etc.

**Comment by dillmo** [comment]
Closed by [0085a60](https://github.com/WIT-Spring-2021-Software-Eng-Group-6/smart-report/commit/0085a60c69d50bc43c0da9fe3830904e4179b469)

**Comment by LeonCChen** [comment]
It's not done

**Comment by LeonCChen** [comment]
b0b81fafb9e3d587a483d62dd169c2e315d637c2
3bad1e97ebe4119c217ea20287803bedff637ee3
9b33f52956872258625854ddf7b1427cba3f5662
