### ISSUE TITLE
Daily/Weekly Newsletters

### ISSUE THREAD

**Issue by ferreirak3atwit** [WIT-Spring-2021-Software-Eng-Group-6/smart-report#5]
Set frequency of newsletter:

  The system shall allow users to change the frequency of newsletters (daily/weekly).

**Comment by dillmo** [comment]
Closed by [9686e26](https://github.com/WIT-Spring-2021-Software-Eng-Group-6/smart-report/commit/9686e262ad1af798aec3ff5a070bf7fdf48e0022).
